import { Subject} from "../types";

export const mockSubjects: Subject[] = [
  {
    id: 1,
    name: "Introduction to Programming",
    code: "CS101",
    department: "Computer Science",
    description: "Covers foundational programming concepts and problem-solving skills.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    code: "MTH201",
    name: "Calculus I",
    department: "Mathematics",
    description: "Introduces limits, derivatives, and basic integration techniques.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    code: "ENG202",
    name: "Academic Writing",
    department: "English",
    description: "Develops writing, research, and critical reading abilities.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    code: "PHY110",
    name: "Physics for Engineers",
    department: "Physics",
    description: "Explores motion, forces, energy, and electrical principles.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    code: "BIO150",
    name: "General Biology",
    department: "Biology",
    description: "Provides an overview of cells, genetics, and living systems.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    code: "HIS301",
    name: "World History",
    department: "History",
    description: "Examines major global events and historical developments.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    code: "ECO210",
    name: "Microeconomics",
    department: "Economics",
    description: "Covers consumer behavior, markets, and pricing mechanisms.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    code: "CHE120",
    name: "General Chemistry",
    department: "Chemistry",
    description: "Introduces atomic structure, bonding, and chemical reactions.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    code: "ART140",
    name: "Design Fundamentals",
    department: "Fine Arts",
    description: "Focuses on visual principles, composition, and creative expression.",
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    code: "BUS250",
    name: "Principles of Management",
    department: "Business",
    description: "Highlights leadership, planning, and organizational decision-making.",
    createdAt: new Date().toISOString(),
  },
];
